//! Session lifecycle types for bore.
//!
//! A session represents a single transfer attempt between a sender and a receiver.
//! Sessions have a well-defined state machine and every transition is explicit.
//!
//! Note: these types define the domain model. The actual session orchestration
//! (networking, crypto, IO) will be implemented in later phases.

use serde::{Deserialize, Serialize};

use crate::error::SessionError;

// ---------------------------------------------------------------------------
// Session identity
// ---------------------------------------------------------------------------

/// Unique identifier for a transfer session.
///
/// Generated by the sender when initiating a transfer. Cryptographically random,
/// 16 bytes (128 bits), represented as lowercase hex.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SessionId(String);

impl SessionId {
    /// Creates a new `SessionId` from a hex string.
    ///
    /// The ID must be exactly 32 hex characters (128 bits).
    pub fn from_hex(hex: &str) -> std::result::Result<Self, SessionError> {
        if hex.len() != 32 || !hex.chars().all(|c| c.is_ascii_hexdigit()) {
            return Err(SessionError::InvalidSessionId);
        }
        Ok(Self(hex.to_lowercase()))
    }

    /// Returns the hex representation of the session ID.
    pub fn as_hex(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for SessionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

// ---------------------------------------------------------------------------
// Roles
// ---------------------------------------------------------------------------

/// The role a peer plays in a transfer session.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TransferRole {
    /// The peer sending files.
    Sender,
    /// The peer receiving files.
    Receiver,
}

impl TransferRole {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Sender => "sender",
            Self::Receiver => "receiver",
        }
    }
}

impl std::fmt::Display for TransferRole {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

// ---------------------------------------------------------------------------
// Transport mode
// ---------------------------------------------------------------------------

/// How the transfer is being transported.
///
/// This is always known and reported to the user — no hidden fallback.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TransportMode {
    /// Direct peer-to-peer connection (LAN or hole-punched WAN).
    Direct,
    /// Traffic forwarded through a relay server.
    Relayed,
    /// Transport mode not yet determined (e.g., during handshake).
    Unknown,
}

impl TransportMode {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Direct => "direct",
            Self::Relayed => "relayed",
            Self::Unknown => "unknown",
        }
    }
}

impl std::fmt::Display for TransportMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

// ---------------------------------------------------------------------------
// Session state machine
// ---------------------------------------------------------------------------

/// The state of a transfer session.
///
/// Transitions are explicit and validated. Invalid transitions produce errors,
/// never panics.
///
/// ```text
/// Created → Waiting → Connected → Transferring → Complete
///    ↓         ↓          ↓            ↓
///  Failed    Failed     Failed       Failed
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SessionState {
    /// Session has been created locally. Not yet advertised or connected.
    Created,
    /// Sender is waiting for a receiver to connect (code has been generated).
    Waiting,
    /// Peers are connected and performing handshake / negotiation.
    Connected,
    /// Encrypted file transfer is in progress.
    Transferring,
    /// Transfer completed successfully.
    Complete,
    /// Transfer failed. Reason is stored elsewhere in the session.
    Failed,
}

impl SessionState {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Created => "created",
            Self::Waiting => "waiting",
            Self::Connected => "connected",
            Self::Transferring => "transferring",
            Self::Complete => "complete",
            Self::Failed => "failed",
        }
    }

    /// Returns whether this state is terminal (no further transitions possible).
    pub const fn is_terminal(self) -> bool {
        matches!(self, Self::Complete | Self::Failed)
    }

    /// Validates that a transition from `self` to `next` is allowed.
    pub fn validate_transition(self, next: Self) -> std::result::Result<(), SessionError> {
        // Any non-terminal state can transition to Failed.
        if next == Self::Failed && !self.is_terminal() {
            return Ok(());
        }

        let valid = matches!(
            (self, next),
            (Self::Created, Self::Waiting)
                | (Self::Waiting, Self::Connected)
                | (Self::Connected, Self::Transferring)
                | (Self::Transferring, Self::Complete)
        );

        if valid {
            Ok(())
        } else {
            Err(SessionError::InvalidTransition {
                from: self.as_str(),
                to: next.as_str(),
            })
        }
    }
}

impl std::fmt::Display for SessionState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

// ---------------------------------------------------------------------------
// Capability negotiation
// ---------------------------------------------------------------------------

/// Feature capabilities that peers can negotiate during handshake.
///
/// Both peers advertise their capabilities. The session uses the intersection.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Capability {
    /// Support for resumable transfers.
    Resume,
    /// Support for compressed transfer (zstd or similar).
    Compression,
    /// Support for directory transfers.
    DirectoryTransfer,
    /// Support for streaming / pipe mode (stdin/stdout).
    StreamMode,
}

impl Capability {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Resume => "resume",
            Self::Compression => "compression",
            Self::DirectoryTransfer => "directory-transfer",
            Self::StreamMode => "stream-mode",
        }
    }
}

impl std::fmt::Display for Capability {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // SessionId tests
    // -----------------------------------------------------------------------

    #[test]
    fn session_id_from_valid_hex() {
        let id = SessionId::from_hex("abcdef0123456789abcdef0123456789").unwrap();
        assert_eq!(id.as_hex(), "abcdef0123456789abcdef0123456789");
    }

    #[test]
    fn session_id_rejects_short_hex() {
        assert!(SessionId::from_hex("abcdef").is_err());
    }

    #[test]
    fn session_id_rejects_non_hex() {
        assert!(SessionId::from_hex("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz").is_err());
    }

    #[test]
    fn session_id_normalizes_to_lowercase() {
        let id = SessionId::from_hex("ABCDEF0123456789ABCDEF0123456789").unwrap();
        assert_eq!(id.as_hex(), "abcdef0123456789abcdef0123456789");
    }

    #[test]
    fn session_id_rejects_empty() {
        assert!(SessionId::from_hex("").is_err());
    }

    #[test]
    fn session_id_rejects_too_long() {
        assert!(SessionId::from_hex("abcdef0123456789abcdef01234567890").is_err());
    }

    #[test]
    fn session_id_display() {
        let id = SessionId::from_hex("abcdef0123456789abcdef0123456789").unwrap();
        assert_eq!(format!("{id}"), "abcdef0123456789abcdef0123456789");
    }

    #[test]
    fn session_id_serde_round_trip() {
        let id = SessionId::from_hex("abcdef0123456789abcdef0123456789").unwrap();
        let json = serde_json::to_string(&id).unwrap();
        let back: SessionId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, back);
    }

    // -----------------------------------------------------------------------
    // State machine tests
    // -----------------------------------------------------------------------

    #[test]
    fn valid_state_transitions() {
        assert!(
            SessionState::Created
                .validate_transition(SessionState::Waiting)
                .is_ok()
        );
        assert!(
            SessionState::Waiting
                .validate_transition(SessionState::Connected)
                .is_ok()
        );
        assert!(
            SessionState::Connected
                .validate_transition(SessionState::Transferring)
                .is_ok()
        );
        assert!(
            SessionState::Transferring
                .validate_transition(SessionState::Complete)
                .is_ok()
        );
    }

    #[test]
    fn any_non_terminal_state_can_fail() {
        assert!(
            SessionState::Created
                .validate_transition(SessionState::Failed)
                .is_ok()
        );
        assert!(
            SessionState::Waiting
                .validate_transition(SessionState::Failed)
                .is_ok()
        );
        assert!(
            SessionState::Connected
                .validate_transition(SessionState::Failed)
                .is_ok()
        );
        assert!(
            SessionState::Transferring
                .validate_transition(SessionState::Failed)
                .is_ok()
        );
    }

    #[test]
    fn terminal_states_reject_transitions() {
        assert!(
            SessionState::Complete
                .validate_transition(SessionState::Created)
                .is_err()
        );
        assert!(
            SessionState::Failed
                .validate_transition(SessionState::Created)
                .is_err()
        );
        assert!(
            SessionState::Complete
                .validate_transition(SessionState::Failed)
                .is_err()
        );
        assert!(
            SessionState::Failed
                .validate_transition(SessionState::Failed)
                .is_err()
        );
    }

    #[test]
    fn invalid_skip_transitions() {
        assert!(
            SessionState::Created
                .validate_transition(SessionState::Transferring)
                .is_err()
        );
        assert!(
            SessionState::Created
                .validate_transition(SessionState::Complete)
                .is_err()
        );
        assert!(
            SessionState::Waiting
                .validate_transition(SessionState::Transferring)
                .is_err()
        );
        assert!(
            SessionState::Waiting
                .validate_transition(SessionState::Complete)
                .is_err()
        );
        assert!(
            SessionState::Connected
                .validate_transition(SessionState::Complete)
                .is_err()
        );
    }

    #[test]
    fn backward_transitions_rejected() {
        assert!(
            SessionState::Waiting
                .validate_transition(SessionState::Created)
                .is_err()
        );
        assert!(
            SessionState::Connected
                .validate_transition(SessionState::Waiting)
                .is_err()
        );
        assert!(
            SessionState::Transferring
                .validate_transition(SessionState::Connected)
                .is_err()
        );
    }

    #[test]
    fn self_transitions_rejected() {
        assert!(
            SessionState::Created
                .validate_transition(SessionState::Created)
                .is_err()
        );
        assert!(
            SessionState::Waiting
                .validate_transition(SessionState::Waiting)
                .is_err()
        );
        assert!(
            SessionState::Connected
                .validate_transition(SessionState::Connected)
                .is_err()
        );
        assert!(
            SessionState::Transferring
                .validate_transition(SessionState::Transferring)
                .is_err()
        );
    }

    #[test]
    fn terminal_detection() {
        assert!(!SessionState::Created.is_terminal());
        assert!(!SessionState::Waiting.is_terminal());
        assert!(!SessionState::Connected.is_terminal());
        assert!(!SessionState::Transferring.is_terminal());
        assert!(SessionState::Complete.is_terminal());
        assert!(SessionState::Failed.is_terminal());
    }

    // -----------------------------------------------------------------------
    // Serde round-trip tests for all types
    // -----------------------------------------------------------------------

    #[test]
    fn transfer_role_serde_round_trip() {
        for role in [TransferRole::Sender, TransferRole::Receiver] {
            let json = serde_json::to_string(&role).unwrap();
            let back: TransferRole = serde_json::from_str(&json).unwrap();
            assert_eq!(role, back);
        }
    }

    #[test]
    fn transport_mode_serde_round_trip() {
        for mode in [
            TransportMode::Direct,
            TransportMode::Relayed,
            TransportMode::Unknown,
        ] {
            let json = serde_json::to_string(&mode).unwrap();
            let back: TransportMode = serde_json::from_str(&json).unwrap();
            assert_eq!(mode, back);
        }
    }

    #[test]
    fn session_state_serde_round_trip() {
        for state in [
            SessionState::Created,
            SessionState::Waiting,
            SessionState::Connected,
            SessionState::Transferring,
            SessionState::Complete,
            SessionState::Failed,
        ] {
            let json = serde_json::to_string(&state).unwrap();
            let back: SessionState = serde_json::from_str(&json).unwrap();
            assert_eq!(state, back);
        }
    }

    #[test]
    fn capability_serde_round_trip() {
        for cap in [
            Capability::Resume,
            Capability::Compression,
            Capability::DirectoryTransfer,
            Capability::StreamMode,
        ] {
            let json = serde_json::to_string(&cap).unwrap();
            let back: Capability = serde_json::from_str(&json).unwrap();
            assert_eq!(cap, back);
        }
    }

    #[test]
    fn transport_mode_unknown_variant() {
        let mode = TransportMode::Unknown;
        assert_eq!(mode.as_str(), "unknown");
        assert_eq!(format!("{mode}"), "unknown");
    }

    // -----------------------------------------------------------------------
    // Exhaustive transition matrix test
    // -----------------------------------------------------------------------

    #[test]
    fn exhaustive_transition_matrix() {
        use SessionState::*;
        let all = [Created, Waiting, Connected, Transferring, Complete, Failed];

        // Define the expected outcomes: (from, to) -> should succeed
        let expected_ok: &[(SessionState, SessionState)] = &[
            (Created, Waiting),
            (Created, Failed),
            (Waiting, Connected),
            (Waiting, Failed),
            (Connected, Transferring),
            (Connected, Failed),
            (Transferring, Complete),
            (Transferring, Failed),
        ];

        for &from in &all {
            for &to in &all {
                let result = from.validate_transition(to);
                let should_be_ok = expected_ok.contains(&(from, to));
                assert_eq!(
                    result.is_ok(),
                    should_be_ok,
                    "transition {from} -> {to}: expected ok={should_be_ok}, got ok={}",
                    result.is_ok()
                );
            }
        }
    }
}
